language: node_js
node_js: node
services: postgresql
before_script: psql -c 'create database palettepicker_test;' -U postgres
deploy:
  provider: heroku
  api_key:
    secure: Tkm5PT4h9ERj/y7MHinmKoz0IzSXTtXjvPkKi/6TfB4IRjAU8seARTTnx2lEaF1UF0fxx3QTUCJUBjr0urK0sEsm1blXVor81VryTSwTl0sP7KTbx87vv3kmHrSlQUlWV6Oq1LjHjkY+57jneRkdcaYLQ+eMBv7MZ3AnbZcA9voIDWgU3tOpE5n0QHMmoo/empCrkrOTNqjKGmL/0G9c8hvL2SSO9KHgvCCVx+6XysQMbysKB9Fv5GyNWbIGalf5XLNUe8cpotw1i7VjExlawDML3dC5dfrn65sFi8yuVJ9Js/s9mdWkz+6rrI8+tfi5D3dUulvH/+UFJqZ0goXlN9k0Qfp1H6teDGxAYzRGvFg2Wpzf7bFHkrGI52r/jcPWFFI9WRB11KHssdDOKtN4jvqPof/83xHzHzkOm7dETsowXh8nFKlMLOYRRc93b4KQX4GBu1r3wxNGl08RIpovREoDvjdQi2ACv7UQVtRld/b32zQe2UeOLRU+Ce4SDiE4I79FU4hF7HHUEshMkhHwbWetHvYfX5+NNY891S88aHj0sODFqi6+M5JJU1x+4TaHoi1sd3X/JzGn56jT9Cqv6xEaF7jw1+yanMhLNG5Op9JSpU3Ns/anJkPkrl4v8mtS/ifr2ZY4pntSqBi7BwWA+enK2w8wTp4VF1ZJ/4lT7tw=
  app: palettepicker-js
  on:
    repo: JSweet314/palette-picker
