language: node_js
node_js: node
services: postgresql
before_script: psql -c 'create database palettepicker_test;' -U postgres
deploy:
  provider: heroku
  api_key:
    secure: mdd6vEy50U4xzb3eM6Optn90DJRAqcVaqw6pH/3G2h4DdnQT8RWl7FQ/mhdLMNqu5UOK+cilgkTqlbD1m8orSytOSYYFVHXTPN/4yTKJH2ZbTwnXi0SQH1QgWvLUx8t0zQUlV3+RuMu6cqVOlPII+L53fup1GpUmBTBkW1YKgFUh2QLsSTc6rb96a1b7aW0le9p7kYTeFZJc4EHUrcVONspme7gMlDcdxp9m362zsHjU4gasLg6Y5dDiWtC+W+lOccS6FSRZ5Xj2GCGypxdw1DzkEnuBKxlEPuJT0dY+jKIxpQ9TeMlDHTFsUBQ2y3DY/TyFcEL9eEQDRiP6+6Cca9RMswGOejqyrOs0AKS2jlWyhhmMShv6nO8bUuBYxeoaaQ6SNlZmCoM4hpqQHcfamtEiqts6kKme6gm1w518kVVBF3/0xPEOy5a8B9sjdUPJiD/aqln16okNeWcJwWdKhhlbBFTL2wkenf8mapDNziwq6OTzR/JV4WNgQxApp9Z+GDHNtLGpECpQueJ5zbyDxnnsPW1TaKCZmbxRV3syXE534r1nr6TokTKKn1N3D5xazYU8xRlebchVmTcI1yE/YRpAEolYxc2D+IO40tH/V7q6OnGvNgeJX4hDAbESWYLrzelVhaFCOYHvKIC8HrxRSHydeQmcxY5OdR5binwttdg=
  app: palettepicker-js
  on:
    repo: JSweet314/palette-picker
