language: node_js
node_js: node
services: postgresql
before_script: psql -c 'create database palettepicker_test;' -U postgres
deploy:
  provider: heroku
  api_key:
    secure: lz0W+/COjx4nJdolokVvD8+EIrxCrquGBeVKej+XGm7nWEENFm0HGcU1vsI21HPpTJFr+lsvhyHKRT5WAaBWnX5sCCcoGNMnexFUGLjIRaqDRDSuLoacPx2RIyTNRLaQhJe5FPt+uuW3hNoD40ucB4ic4JEbWW7LvGhN1XHKDyruy+C/CTo1cGVOFQbzYO57eMinr7JdZfoiIl5re8jc4jezfqKtlhtdevrS9aWaEDZjw5jNFkOM+Vu/L3jhdO0tI/H5OYFTVkil7idiRt7Zlv1VSiJFHXqExfehzanNyNspjdxuOEBJpqeKpmOuYOCUSmrsVIBBoDWhUVgCPvDh+I/eONzb+j/C7gnwxvE3xRiiQZnrBPhFATCbjLVDLv1bk14XegBOlddRKVxOiWKVqlu2h5F6j4c+uFwBgYpVJHYXzQJ4AkqlqLPsjCkddrDpb6KtD9Iig0teVLOGDmfrpocHT6lAiiUte/+65J2JHdG+PFAuI68H0s5LbWEe5yg+x11XgHisGVn55Fm4A5whSEiP23vfQT1Y6bG/AT6IOvGOCfEuAhyFkY2sCs2+NqoV1vYL5R4kFnEn1qgI5/VYNtHbCC8OlWvwOMK/ONR3rPxL9YSepm5IA2mPnC0Joi2JP+UXdydgVWOEsP2iFNDG+xK8qlFOGpOc5r1UN6S5xSA=
  app: palettepicker-js
  on:
    repo: JSweet314/palette-picker
