language: node_js
node_js: node
services: postgresql
before_script: psql -c 'create database palettepicker_test;' -U postgres
deploy:
  provider: heroku
  api_key:
    secure: BUwjEmZVHfraRR9878nFA+bVOUTmS5XwXXU4u0846hpZP1ivJtkg92/DOqCNecD5lTwdc3XhuWs+Dg+Wbq777dXEsyHX7ptUlo14BJbfONAFpkkAh9k8SzTiEk1kiByfHrIiRRGuP+UH4/ZGwxSAhJhVfb00CbTiq/T72ZeNRL/B97btfGBbrU9NsAgCAr6wMtdGwp38t2wzXZ6keh3cWImq8LdSKs1ZE0R3j0Wk4fwB23/02nYfspdTlC+nvsLCTxy3Lo0R/LD09t9oPP9wmXlsMfIaLJB0bWZ78sPl7Stp60QR6lITN86MyV7/UaaYU7WAsFNjkWibTnZplYaOq5B3q5/sLmokQBKTj+BJhzNY8/1x+UXrrYEvRELwYEXpkMGclAqW6X12+OppvZxggzIYH22MmUbdZPnq8vZ1VKbRQhtkaKvojMEWmsL2I+CdfgitKznrMYgRNo4uWr/QHDqAvKzrtUicGvEaiiwILg54SKvD8QIhXhOHukhbJuJwH8giZCkSRtgtI5XufsrwjY6AOQZi4Y2tHmsGcUT9EqndPIV1n9Rl1IJlUkm8K0Ah0tvYmJs5EifCj1ZILywoG+VY1+l1IBPBKmk7qhfWODfYpnKuog/+UXw2/b4QsQihDGRC3iIYch917QqHoQgxu9PDiSdtjPbuRPVdPMyEPhc=
  app: palettepicker-js
  on:
    repo: JSweet314/palette-picker
