language: node_js
node_js: node
services: postgresql
before_script: psql -c 'create database palettepicker_test;' -U postgres
deploy:
  provider: heroku
  api_key:
    secure: bd/b5XDIBw6289fYD+Zq62VkOLYjZd+asQbcUausLWQfq5mSGsGv/jHhtnVOE6pnJj+quKtZHBhYrgmZ8MkKTmaaI/Tco4H/s32/+Y9SpUpvuU7lI9zxIqEZBCd1QJVJt9LE/OsqY3prSdwLcXPPMbFCgc/8jJoYmNhR60EMpsqURrZCc65l97K60LoMGeyBoYJeA6Uhx5/ba47E2gRgLopAy/eyMXFJHW3v8xkWC6Vx7GbtUqG14G6bsO93yZR/mXonMvjsQ0nhMBO4rPl/Pf/RzrMVYbiFAYIu87dvk5tChp54XWoPUGLFZUU4H/59s/XrQwwITopiHoZMEQR5bCUoDYXmY5NVrtAW/iXMOOMdowJLvQwmlv15JBuc3n+B7PUUxU6jVr3/kSeWEoIITovuodVMiwO4kvb6r7ceAEm9EKT8B6dfQrb5nt0ChurRVAIKqNkGW6NZXbuNkA3ts20yduYYOqwmmvjdPcC/7BLsq9bIA56iIw7DB/xGqycbABAlXmWVYuObGQw0m6+Is/dXBakHbzONnzXnpVSWJgpRW4jHgfeC9UL9IN83wMvUfVLmmKXj8aPym6YCtpHkqGOkeN3PrQtIf3gG3c2BX/VBoAOLPlsUmkwDHAajANWOqE0mA8i/BbliHbvs9evv316wKJRRB5+iNmNi6n1Q2Lo=
  app: palettepicker-js
  on:
    repo: JSweet314/palette-picker
skip-cleanup: true